[package]
name = "hongbot-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
dotenvy = "0.15.6"
env_logger = "0.10.0"
log = "0.4.17"
regex = "1.7.0"
thiserror = "1.0.38"
